### ISSUE TITLE
Missmatch opportunities object and example

### ISSUE THREAD

**Issue by DylanBartels** [Element84/stat-api-spec#103]
There are several mismatches in the opportunitiesCollection documented object and the example.
- In the [object](https://github.com/Element84/stat-api-spec/blob/main/opportunity/README.md) the product_id is on the Feature  and in the example it is [in the properties](https://github.com/Element84/stat-api-spec/blob/main/examples/OpportunityCollection.json?short_path=8d5280f#L16).
- Constrains is it's part of properties but it's own field of the feature in the object definition
- In the object the links are part of featureCollection and the example of feature

**Comment by matthewhanson** [comment]
Resolved in a few different PRs.  constraints is now parameters, product_id is in properties
