### ISSUE TITLE
Change data type of datetime in order request?

### ISSUE THREAD

**Issue by m-mohr** [Element84/stat-api-spec#117]
Does it make sense that the datetime in POST /orders is a array instead of a string as in STAC search? This would be easier to validate in JSON Schema and OpenAPI.

**Comment by captaincoordinates** [comment]
Current string strategy is similar to how [STAC API spec](https://github.com/radiantearth/stac-api-spec/tree/release/v1.0.0/item-search#query-parameter-table) provides date ranges.

**Comment by captaincoordinates** [comment]
Is there a good reason for the current `datetime` type being [ISO8601 Time Interval](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals). Do we actually need to support durations, or durations and timestamps? Why not simply timestamps or unspecified, as in [STAC API spec](https://github.com/radiantearth/stac-api-spec/tree/release/v1.0.0/item-search#query-parameter-table)?
