### ISSUE TITLE
Do we need an informational key/value field in products?

### ISSUE THREAD

**Issue by nic-planet** [Element84/stat-api-spec#157]
We might want to add a field that supports key-values (I'd suggest free-form for now) to describe products with properties like sensor_type, resolution, ... 

Example: Up42 showing different products by different providers, but could even make sense for different products by the same provider.

This _could_ be encoded in the JSON schema for filters by providing a single value, but it seems like a slight mis-use of that field.

**Comment by m-mohr** [comment]
=> STAC :-)

**Comment by nic-planet** [comment]
Please elaborate :)

**Comment by m-mohr** [comment]
I just mean, do it as STAC does it.

1. People can re-use the field names and extensions from STAC if available (e.g. version and deprecated fields from the version extension)
2. People can just put additional properties in the top-level object as it's JSON

**Comment by nic-planet** [comment]
Does this mean 
- users can already do this, no need for action on our side, or
- we need to replicate something in the spec to support this, STAC-style?

**Comment by m-mohr** [comment]
>     * users can already do this, no need for action on our side, or

Yes, we may want to explicitly call it out in the spec though.
