### ISSUE TITLE
Omit stat_version?

### ISSUE THREAD

**Issue by m-mohr** [Element84/stat-api-spec#90]
The version number can be derived from the conformance class, is the stat_version really required?

The same applies to stat_extensions. If the focus here is API, then it should follow OGC / STAC API and use conformance classes. 
If STAT also supports "static" like STAC spec (and is independantly versioned), then you may want the additional properties. Otherwise it seems like duplicate information.

**Comment by matthewhanson** [comment]
This makes sense and will remove stat_version and stat_extensions

**Comment by m-mohr** [comment]
The only issue is that conformance classes may not lead to a document that can be used for validation. Otherwise sounds all good.
