### ISSUE TITLE
datetime in order is confusing

### ISSUE THREAD

**Issue by m-mohr** [Element84/stat-api-spec#93]
The datetime field in the Order Spec is relatively confusing if coming from STAC and also in general.

datetime as a name indicates a single instance to me, but instead it's actually in interval. Maybe choose a name that is more explicit (and does't "conflict" with STAC)?

**Comment by jsignell** [comment]
I think this `datetime` field is more similar to the one in item-search in the stac-api-spec. In general the objects in this spec tend much more towards request-like objects rather than response-like objects if that makes sense.

**Comment by m-mohr** [comment]
Makes sense.
