### ISSUE TITLE
Geometry references

### ISSUE THREAD

**Issue by matthewhanson** [Element84/stat-api-spec#99]
A potential use case, especially with recurring tasks, is the reuse of geometry in orders. 

To prevent passing around large complex geometries, these can be stored by the provider and later referenced in the order.

Geometry is a required parameter, but perhaps should be allowed to be GeoJSON or a reference such as a URI.

**Comment by captaincoordinates** [comment]
Suggested geometry structure:

| field | type | description | examples |
|-----|------|------------|----------|
| type | string | Identifies how the value field should be parsed and interpreted | `GeoJSON`<br />`GeometryIdentifier`<br />`OGCFeatureURI` |
| value | string | Provides the geometry according to the type field | `{"type": "Feature", ...}`<br />`fe24dc99-65ec-44ac-bcc3-556067af8309`<br />`https://domain/collections/123/items/321` |
